name: CI

on:
  push:
    branches: [ main ]
  pull_request_target:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test on iOS 14 with Xcode 12
      run: set -o pipefail && xcodebuild -enableCodeCoverage YES -scheme gh-sonar-noapp-int-test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' clean build test | xcpretty
    - name: Create code coverage report
      run: ./scripts/xccov-to-sonarqube-generic.sh /Users/runner/Library/Developer/Xcode/DerivedData/gh-sonar-noapp-int-test*/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml
    - name: Store coverage for sonar job
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: sonarqube-generic-coverage.xml

  sonar:
    needs: build
    if: github.repository == 'MarcoEidinger/gh-sonar-noapp-int-test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get coverage from build job
      uses: actions/download-artifact@v1
      with:
        name: coverage
    - name: Scan (main branch)
      if: github.event_name == 'push'
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Scan (PR from repo)
      if: github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name == github.repository
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.pullrequest.provider=github
          -Dsonar.pullrequest.github.repository=${{ github.repository }}
          -Dsonar.pullrequest.github.token.secured=${{ secrets.GITHUB_TOKEN }}
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Scan (PR from fork)
      if: github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.pullrequest.provider=github
          -Dsonar.pullrequest.github.repository=${{ github.repository }}
          -Dsonar.pullrequest.github.token.secured=${{ secrets.GITHUB_TOKEN }}
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Add comment with link to SonarCloud report
      if: github.event_name == 'pull_request_target'
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'SonarCloud Analysis will be available: https://sonarcloud.io/dashboard?id=gh-sonar-noapp-int-test&pullRequest=' + context.issue.number
            })


