# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow helps you trigger a SonarCloud analysis of your code and populates
# GitHub Code Scanning alerts with the vulnerabilities found.
# Free for open source project.

# 1. Login to SonarCloud.io using your GitHub account

# 2. Import your project on SonarCloud
#     * Add your GitHub organization first, then add your repository as a new project.
#     * Please note that many languages are eligible for automatic analysis,
#       which means that the analysis will start automatically without the need to set up GitHub Actions.
#     * This behavior can be changed in Administration > Analysis Method.
#
# 3. Follow the SonarCloud in-product tutorial
#     * a. Copy/paste the Project Key and the Organization Key into the args parameter below
#          (You'll find this information in SonarCloud. Click on "Information" at the bottom left)
#
#     * b. Generate a new token and add it to your Github repository's secrets using the name SONAR_TOKEN
#          (On SonarCloud, click on your avatar on top-right > My account > Security
#           or go directly to https://sonarcloud.io/account/security/)

# Feel free to take a look at our documentation (https://docs.sonarcloud.io/getting-started/github/)
# or reach out to our community forum if you need some help (https://community.sonarsource.com/c/help/sc/9)

name: SonarCloud analysis

on:
  push:
    branches: [ main ]
  pull_request_target:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test on iOS 14 with Xcode 12
      run: set -o pipefail && xcodebuild -enableCodeCoverage YES -scheme gh-sonar-noapp-int-test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' clean build test | xcpretty
    - name: Create code coverage report
      run: ./scripts/xccov-to-sonarqube-generic.sh /Users/runner/Library/Developer/Xcode/DerivedData/gh-sonar-noapp-int-test*/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml
    - name: Store coverage for sonar job
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: sonarqube-generic-coverage.xml

  sonar:
    needs: build
    if: github.repository == 'Onoppe/gh-sonar-noapp-int-test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get coverage from build job
      uses: actions/download-artifact@v1
      with:
        name: coverage
    - name: Scan (main branch)
      if: github.event_name == 'push'
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Scan (PR from repo)
      if: github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name == github.repository
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.pullrequest.provider=github
          -Dsonar.pullrequest.github.repository=${{ github.repository }}
          -Dsonar.pullrequest.github.token.secured=${{ secrets.GITHUB_TOKEN }}
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Scan (PR from fork)
      if: github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.pullrequest.provider=github
          -Dsonar.pullrequest.github.repository=${{ github.repository }}
          -Dsonar.pullrequest.github.token.secured=${{ secrets.GITHUB_TOKEN }}
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Add comment with link to SonarCloud report
      if: github.event_name == 'pull_request_target'
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'SonarCloud Analysis will be available: https://sonarcloud.io/dashboard?id=gh-sonar-noapp-int-test&pullRequest=' + context.issue.number
            })


